name: CoDe Alliance
highlighter: rouge
exclude: [README.md]
timezone: Europe/Copenhagen
url: http://alliance.praqma.com
markdown: kramdown
permalink:  none


permalink: /:categories/:title/

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  -
    scope:
      path: "" # any file
    values:
      layout: default
